host:        127.0.0.1
port:        4000
baseurl:     /

name:        "Welcome to the Void"

source:      .
destination: ./_site
layouts:     ./_layouts

markdown:    redcarpet
pygments:    true

permalink:   /news/:year/:month/:title.html

snow:        0

gems:
  - jekyll-redirect-from
